[GLOBAL]
pants_version = "2.30.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.flake8",
    "pants.backend.docker",
    "pants.backend.experimental.go",
]

[source]
root_patterns = [
    "/",
    "/examples",
    "/examples/go_hello",
    "/infra",
    "/uv_only_monorepo",
    "/uv_only_monorepo/apps",
    "/uv_only_monorepo/libs/math_library/src",
]

[python]
interpreter_constraints = ["CPython>=3.14,<3.15"]

[python-infer]
use_rust_parser = true

[black]
config = "pyproject.toml"

[isort]
config = ["pyproject.toml"]

[flake8]
config = ".flake8"

[test]
timeout_default = 60

[update-build-files]
check = false
fmt = true

[tailor]
check = false
build_file_name = "BUILD"
ignore_paths = [
    "infra/docker_linux/**",
    "sample_flask/**",
    "uv_only_monorepo/**/.venv/**",
    "uv_only_monorepo/**/__pycache__/**",
    "uv_only_monorepo/apps/only_uv_monorepo.egg-info/**",
]

[docker]
default_repository = "ercot-lmp"
build_args = []
build_target_stage = ""

[anonymous-telemetry]
enabled = false
