FROM postgres:16-alpine

# Environment variables for default user and database
ENV POSTGRES_USER=ercot_user \
    POSTGRES_PASSWORD=ercot_pass \
    POSTGRES_DB=ercot_db

# Copy SQL initialization files from the build context
# Pants stages them in the root of the context
COPY *.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
