python_distribution(
    name="dist",
    dependencies=["//uv_only_monorepo/libs/math_library/src/math_library:math_library"],
    provides=python_artifact(
        name="math-library",
        version="0.1.0",
    ),
)
